'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
Friend Module LicenseResources
    
    Private resourceMan As Global.System.Resources.ResourceManager
    
    Private resourceCulture As Global.System.Globalization.CultureInfo
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pss.Cisco.LicenseResources", GetType(LicenseResources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Authenticating.
    '''</summary>
    Friend ReadOnly Property AuthenticatingTxt() As String
        Get
            Return ResourceManager.GetString("AuthenticatingTxt", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to An unexpected error occurred while authenticating your license key.  Do you want to authenticate your license by sending  it to us via email or post instead?
    '''
    '''Click &quot;No&quot; and then &quot;Install&quot; to try again.
    '''
    '''Click &quot;Yes&quot; to save your license to a file.   Send this file to us and we will authenticate and return it, so that you can load it using the &quot;Load License&quot; button.
    '''
    '''Error: {0}.
    '''</summary>
    Friend ReadOnly Property AuthenticationErrorMsg() As String
        Get
            Return ResourceManager.GetString("AuthenticationErrorMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Authentication Error.
    '''</summary>
    Friend ReadOnly Property AuthenticationErrorTitle() As String
        Get
            Return ResourceManager.GetString("AuthenticationErrorTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The number of installations allowed for this license key has been exceeded.   .
    '''</summary>
    Friend ReadOnly Property AuthenticationsExceededMsg() As String
        Get
            Return ResourceManager.GetString("AuthenticationsExceededMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure you want to uninstall the current license?.
    '''</summary>
    Friend ReadOnly Property ConfirmUninstallMsg() As String
        Get
            Return ResourceManager.GetString("ConfirmUninstallMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Confirm License Uninstall.
    '''</summary>
    Friend ReadOnly Property ConfirmUninstallTitle() As String
        Get
            Return ResourceManager.GetString("ConfirmUninstallTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unable to connect to the License Authentication Server via the internet to authenticate your license on this computer. Do you want to authenticate your license by sending  it to us via email or post instead?
    '''
    '''Click &quot;No&quot; to fix your internet or firewall settings and then click the &quot;Install&quot; button to try again.
    '''
    '''Click &quot;Yes&quot; to save your license to a file.   Send this file to us and we will authenticate and return it, so that you can load it using the &quot;Load License&quot; button..
    '''</summary>
    Friend ReadOnly Property ConnectionErrorMsg() As String
        Get
            Return ResourceManager.GetString("ConnectionErrorMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Your evaluation period has expired.
    '''</summary>
    Friend ReadOnly Property EvaluationExpiredMsg() As String
        Get
            Return ResourceManager.GetString("EvaluationExpiredMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Your evaluation is no longer valid.
    '''</summary>
    Friend ReadOnly Property EvaluationInvalidMsg() As String
        Get
            Return ResourceManager.GetString("EvaluationInvalidMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The key ({0}) is not a valid license key for this product..
    '''</summary>
    Friend ReadOnly Property InvalidAuthenticationKeyMsg() As String
        Get
            Return ResourceManager.GetString("InvalidAuthenticationKeyMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid License Key.
    '''</summary>
    Friend ReadOnly Property InvalidAuthenticationKeyTitle() As String
        Get
            Return ResourceManager.GetString("InvalidAuthenticationKeyTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The license is not valid for this computer.  This could be because you have changed the computer name since installing the license.
    '''
    '''Licensed Computer: {0}
    '''This Computer: {1}
    '''
    '''You may need to install a new license using the original License Key provided to you when you purchased the product.  .
    '''</summary>
    Friend ReadOnly Property InvalidComputerMsg() As String
        Get
            Return ResourceManager.GetString("InvalidComputerMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Not a valid License Settings File.
    '''</summary>
    Friend ReadOnly Property InvalidILSFile() As String
        Get
            Return ResourceManager.GetString("InvalidILSFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The key ({0}) is not a valid license key for this product..
    '''</summary>
    Friend ReadOnly Property InvalidKeyMsg() As String
        Get
            Return ResourceManager.GetString("InvalidKeyMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid License Key.
    '''</summary>
    Friend ReadOnly Property InvalidKeyTitle() As String
        Get
            Return ResourceManager.GetString("InvalidKeyTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} - Invalid License.
    '''</summary>
    Friend ReadOnly Property InvalidLicenseTitle() As String
        Get
            Return ResourceManager.GetString("InvalidLicenseTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The license is not a valid license for this product ({0}).  It is a license for another product ({1})..
    '''</summary>
    Friend ReadOnly Property InvalidProductMsg() As String
        Get
            Return ResourceManager.GetString("InvalidProductMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The license file contents have been modified and the license is no longer valid.  You may need to reinstall the license using the original License Key provided to you when you purchased the product..
    '''</summary>
    Friend ReadOnly Property InvalidSignatureMsg() As String
        Get
            Return ResourceManager.GetString("InvalidSignatureMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to License.lic.
    '''</summary>
    Friend ReadOnly Property LicenseFile() As String
        Get
            Return ResourceManager.GetString("LicenseFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to License Files|*.lic.
    '''</summary>
    Friend ReadOnly Property LicenseFileFilter() As String
        Get
            Return ResourceManager.GetString("LicenseFileFilter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to License Installed.
    '''</summary>
    Friend ReadOnly Property LicenseInstalledTxt() As String
        Get
            Return ResourceManager.GetString("LicenseInstalledTxt", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Load License from File.
    '''</summary>
    Friend ReadOnly Property LoadLicenseTitle() As String
        Get
            Return ResourceManager.GetString("LoadLicenseTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No License Installed.
    '''</summary>
    Friend ReadOnly Property NoLicenseInstalledTxt() As String
        Get
            Return ResourceManager.GetString("NoLicenseInstalledTxt", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to An error ({0}) occurred while reading the license from file ({1}).  
    '''
    '''Ensure you have sufficient privileges to read from the license file..
    '''</summary>
    Friend ReadOnly Property ReadErrorMsg() As String
        Get
            Return ResourceManager.GetString("ReadErrorMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Error Reading License.
    '''</summary>
    Friend ReadOnly Property ReadErrorTitle() As String
        Get
            Return ResourceManager.GetString("ReadErrorTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to An unexpected error ({0}) occurred while reading the license. .
    '''</summary>
    Friend ReadOnly Property ReadXmlErrorMsg() As String
        Get
            Return ResourceManager.GetString("ReadXmlErrorMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Save License to File.
    '''</summary>
    Friend ReadOnly Property SaveLicenseTitle() As String
        Get
            Return ResourceManager.GetString("SaveLicenseTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The license has not been authenticated..
    '''</summary>
    Friend ReadOnly Property UnauthenticatedLicenseMsg() As String
        Get
            Return ResourceManager.GetString("UnauthenticatedLicenseMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to An error ({0}) occurred while deleting the license file ({1}).  
    '''
    '''Ensure you have sufficient privileges to delete the license file..
    '''</summary>
    Friend ReadOnly Property UninstallErrorMsg() As String
        Get
            Return ResourceManager.GetString("UninstallErrorMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Error Uninstalling License.
    '''</summary>
    Friend ReadOnly Property UninstallErrorTitle() As String
        Get
            Return ResourceManager.GetString("UninstallErrorTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unknown Product.
    '''</summary>
    Friend ReadOnly Property UnknownProductTxt() As String
        Get
            Return ResourceManager.GetString("UnknownProductTxt", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please Wait....
    '''</summary>
    Friend ReadOnly Property WaitTxt() As String
        Get
            Return ResourceManager.GetString("WaitTxt", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to An error ({0}) occurred while writing the license to file ({1}).  
    '''
    '''Ensure you have sufficient privileges to write to the license file..
    '''</summary>
    Friend ReadOnly Property WriteErrorMsg() As String
        Get
            Return ResourceManager.GetString("WriteErrorMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Error Writing License.
    '''</summary>
    Friend ReadOnly Property WriteErrorTitle() As String
        Get
            Return ResourceManager.GetString("WriteErrorTitle", resourceCulture)
        End Get
    End Property
End Module
